THISDIR = $(shell pwd)
XRAY_URL_BASE := https://github.com/felix-fly/xray-openwrt/releases/latest/download/

XRAY_NAME := xray-linux-mipsle
XRAY_URL := $(XRAY_URL_BASE)/$(XRAY_NAME).tar.gz

all:
  echo ${XRAY_URL};

clean:

romfs:
