on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: init
        run: |
          sudo apt-get update
          sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot kmod cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin
      - name: build
        run: |
          mkdir /opt/bin
          git clone --depth=1 https://github.com/hanwckf/rt-n56u.git /opt/rt-n56u
          cd /opt/rt-n56u/toolchain-mipsel
          sh dl_toolchain.sh
          cd /opt/rt-n56u/trunk
          wget https://raw.githubusercontent.com/f763180872/xray-padavan-k2p/master/k2p.config -O configs/templates/K2P.config

          wget https://raw.githubusercontent.com/f763180872/xray-padavan-k2p/master/padavan/user/Makefile -O user/Makefile

          # build-in xray
          mkdir -p user/xray
          wget -P user/xray/ https://raw.githubusercontent.com/f763180872/xray-padavan-k2p/master/padavan/xray/Makefile
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_V2RAY=y/CONFIG_FIRMWARE_INCLUDE_V2RAY=n/' configs/templates/K2P.config
          sed -i 's/CONFIG_FIRMWARE_INCLUDE_XRAY=n/CONFIG_FIRMWARE_INCLUDE_XRAY=y/' configs/templates/K2P.config
          fakeroot ./build_firmware_modify K2P
          mv /opt/rt-n56u/trunk/images/*.trx /opt/bin/k2p_xray.trx
      - name: Upload artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.UPLOAD_KEY }}"
          prerelease: false
          files: |
            /opt/bin/*.trx
